automate:
  browser:
    default: chrome
  drivers:
    chrome:
      driver : '/.../chromedriver'
  scenario:
    folder: '/.../scenario'
  specs:
    folder: '/.../specs'
  logs:
    enable: true
    folder: '/.../logs'
  pages:
    folder: '/.../pages'
  logics:
    namespaces:
      demo: 'Demo\Logics'
    valueAtException: false